### ISSUE TITLE
Need advice 

### ISSUE THREAD

**Issue by kroegen** [shinoki77/ASUS-X299-Hackintosh#1]
First of all I want to thank you for your work and for sharing this configuration. It saved me a lot of time and helped me to build a PC of my dream which I use as a working tool.

I used your BASE-EFI folder last year to install my own Hackintosh. I followed the steps in Readme and got everything working in a day. The OpenCore version was 0.6.9 (2021.05.03) for Big Sur. Now I want to update it to the latest version but I am not sure if it will work. And I need your advice related to in which order I need to update and what. 
Will the latest version of OpenCore work with Big Sure without OS update? 
Is it possible to use Install MacOS Monterey app from AppStore? 
Or maybe it will be easier to completly reinstall MacOS from scratch?

I've already have a complete clone of my system on other ssd for testing pruposes. My plan is to use this app and then update OpenCore if it will have some issues. But maybe you have a shorter way. Thanks for any form of reply!

**Comment by shinoki77** [comment]
Hi, yes Open core versions are backwards compatible so the newest one will work with Big Sur.  

I'd try to update Opencore and make sure it works first on your machine.  Then you can go ahead and install macOS Monterey from the app store or through system preferences.  Of course have a backup just in case.  Unfortunately I don't have my X299 components anymore but I believe OpenCore 0.8.1 vs 0.8.2 config is the same so you just need to update the kexts and bootloader itself to the latest.  You can use something like https://github.com/ic005k/OCAuxiliaryTools to help update if you don't want to do it manually 

Hope this helps!
